[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util" }
bitvec = { workspace = true }
fxhash = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }
rayon = { workspace = true }

