[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
util = { path = "../util" }
fxhash = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }
rayon = { workspace = true }
